export enum statusPurchaseType {
  WAITING_PAYMENT = 'WAITINGPAYMENT',
  SCHEDULE_MEETING = 'SCHEDULEMEETING',
  SCHEDULED_MEETING = 'SCHEDULEDMEETING',
  WAITING_SPREADSHEET = 'WAITINGSPREADSHEET',
  SPREADSHEET_SENT = 'SPREADSHEET SENT',
  SCHEDULE_RETURN = 'SCHEDULE RETURN',
  FINALIZED = 'FINALIZED',
}
